name: Bug Report
description: Submit a bug report
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the issue briefly. You are encouraged to provide screenshots, videos, code-snippets, error messages or other to further explain your problem.
      placeholder: Describe your issue!
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen in a clear and concise way
      placeholder: Describe the expected behavior!
    validations:
      required: true
      
  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction steps
      description: How do you trigger this bug? Please walk us through it step by step.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
      
  - type: input
    id: bug-version
    attributes:
      label: Version (bug)
      description: Which version are you experiencing the issue on?
      placeholder: 5.X.X
    validations:
      required: true
      
  - type: input
    id: working-version
    attributes:
      label: Version (working)
      description: Did it work on a previous version? If so, which version?
      placeholder: 5.X.X
